[package]
name = "dora-node"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
dora-node-api = { git = "https://github.com/dora-rs/dora.git" }
eyre = "0.6.8"
futures = { version = "0.3.31", features = ["thread-pool"] }
futures-timer = "3.0.3"
rand = "0.9.2"
zenoh = "1.5"
